### ISSUE TITLE
How do I create a file in a specific directory

### ISSUE THREAD

**Issue by kennethngedoFCMB** [timheuer/base64-to-file#15]
For example I want the file to be create in `./lib/assets/secrets`, How do I achieve that?

**Comment by timheuer** [comment]
Have you tried setting that path as the `fileName` parameter? 

```
fileName: ./lib/assets/secrets/foo.txt
```

**Comment by timheuer** [comment]
This is now enabled in v1.1 tag by specifying the `fileDir` location in addition to the `fileName`
