### ISSUE TITLE
Please return absolute path as outputs.filePath

### ISSUE THREAD

**Issue by filipkowicz** [timheuer/base64-to-file#3]

**Comment by filipkowicz** [comment]
works with 1.0.2 - please update docs on actions market 
it still points to v1

**Comment by timheuer** [comment]
Hi @filipkowicz it already does...see: https://github.com/timheuer/base64-to-file/commit/c473f25783492150b72e0baf8ccf6f652e7acba2/checks?check_suite_id=412292375#step:4:4 for example.

**Comment by filipkowicz** [comment]
all working, closing then, it was my mistake to use older version
