### ISSUE TITLE
Upgrade to Node 16

### ISSUE THREAD

**Issue by danielz-nenda** [timheuer/base64-to-file#32]
Everywhere this action is used, this warning is now showing:
`[build]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: timheuer/base64-to-file`

**Comment by timheuer** [comment]
Thank you!

@all-contributors please add @danielz-nenda for bug
