### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by RobbieFrodsham** [timheuer/base64-to-file#40]
Runs of this workflow trigger the following advisory in github actions:

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by timheuer** [comment]
Updated and updated `v1` and `v1.2` tags -- thanks for the reminder!

**Comment by timheuer** [comment]
@all-contributors please add @RobbieFrodsham for bugs
