### ISSUE TITLE
Remove printing all environment variables

### ISSUE THREAD

**Issue by Blarkdackbyte** [timheuer/base64-to-file#42]
Hi!

I would prefer not to see all environment variables in the logs :)
Just remove this line?

https://github.com/timheuer/base64-to-file/blob/c4a503294433fc78768118aea23f8353dfde89e2/index.js#L18

**Comment by timheuer** [comment]
Good bug thanks. Will put this behind a debug log check. Never removed during dev 😕

**Comment by timheuer** [comment]
@all-contributors please add @Blarkdackbyte for bugs

**Comment by Blarkdackbyte** [comment]
Oh, what an honor! Thank you! :)

**Comment by timheuer** [comment]
@all-contributors please add @Blarkdackbyte for code
